### PR TITLE
Faster Implementation of collage building

### PR DESCRIPTION
**Pull request by noamlif**
Uses map and lambda to generate a more efficient code,
builds collage in 1-3 seconds (for the average cache)

### CODE REVIEW

**Comment by nitrogenc** [comment]
Hi.
Until now, I wasn't worry in any way about collage speed.
Now that Python3 is supported, there's a performance issue with collage building under Python3.
Will have a look at the issue/your proposal and run some tests.

To be continued...

**Comment by noamlif** [comment]
Since I use Python3 I also have the implementation using a byte stream, will send it over

**Comment by noamlif** [comment]
@nitrogenc 
I updated this branch by the last update in your repository and added the Bytes stream implementation of the faster collage

**Comment by nitrogenc** [comment]
Much appreciated.
Python2 performance remains unchanged, and Python3 performance is awesomely improved (8x faster on a 1000-tile collage).

Thanks a lot for your pull request.

**Pull request merged**
